version: "2"

services:
  app:
    #image: arizawan/monicahq-supervisor
    image: monicahq/monicahq
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      # generate with `pwgen -s 32 1` for instance:
      - APP_KEY=YOU_KEY
      - APP_DEBUG=true
      - DB_HOST=db
      - DB_DATABASE=monica_db
      - DB_USERNAME=monica-user
      - DB_PASSWORD=secret
      - MAIL_MAILER=smtp
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_ENCRYPTION=tls
      - MAIL_USERNAME=YOUR_EMAIL
      - MAIL_PASSWORD=YOUR_PASS
      - MAIL_FROM_ADDRESS=YOUR_EMAIL
      - MAIL_FROM_NAME="Monica Personal CRM"
      - APP_URL=http://localhost:8080
      - TZ=Europe/Amsterdam
      - QUEUE_CONNECTION=database
    volumes:
      - ./monicahq_f:/var/www/monica/storage
    restart: always

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica_db
      - MYSQL_USER=monica-user
      - MYSQL_PASSWORD=secret
    volumes:
      - ./monicahq-mysql:/var/lib/mysql
    restart: always